import { StyleSheet } from 'react-native';
import type { ThemeColors } from '@/constants/colors';

export const createStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    screen: {
      backgroundColor: colors.background,
      flex: 1,
    },
    content: {
      gap: 20,
      paddingHorizontal: 20,
      paddingTop: 24,
      paddingBottom: 24,
    },
    header: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    profileRow: {
      alignItems: 'center',
      flex: 1,
      flexDirection: 'row',
      gap: 12,
    },
    avatar: {
      borderRadius: 10,
      height: 40,
      overflow: 'hidden',
      width: 40,
    },
    avatarImage: {
      height: '100%',
      width: '100%',
    },
    avatarFallback: {
      alignItems: 'center',
      backgroundColor: colors.accent,
      borderRadius: 10,
      height: 40,
      justifyContent: 'center',
      width: 40,
    },
    avatarInitial: {
      color: colors.primary,
      fontSize: 18,
      fontWeight: '700',
    },
    headerCopy: {
      flex: 1,
    },
    greeting: {
      color: colors.text,
      fontSize: 20,
      fontWeight: '700',
    },
    subtitle: {
      color: colors.textMuted,
      fontSize: 13,
      marginTop: 2,
    },
    headerIcon: {
      alignItems: 'center',
      borderColor: colors.border,
      borderRadius: 12,
      borderWidth: 1,
      height: 40,
      justifyContent: 'center',
      width: 40,
    },
    headerActions: {
      flexDirection: 'row',
      gap: 8,
    },
    hero: {
      backgroundColor: colors.accent,
      borderRadius: 24,
      flexDirection: 'row',
      minHeight: 168,
      overflow: 'hidden',
      paddingHorizontal: 20,
      paddingVertical: 22,
    },
    heroDecorOne: {
      backgroundColor: colors.secondary,
      borderRadius: 80,
      height: 160,
      opacity: 0.22,
      position: 'absolute',
      right: -20,
      top: -40,
      width: 160,
    },
    heroDecorTwo: {
      backgroundColor: colors.secondary,
      borderRadius: 50,
      height: 100,
      opacity: 0.18,
      position: 'absolute',
      right: 40,
      top: 50,
      width: 100,
    },
    heroCopy: {
      flex: 1,
      zIndex: 1,
    },
    heroIcon: {
      alignItems: 'center',
      backgroundColor: colors.primary,
      borderRadius: 12,
      height: 40,
      justifyContent: 'center',
      marginBottom: 12,
      width: 40,
    },
    heroLabel: {
      color: colors.primary,
      fontSize: 14,
      fontWeight: '600',
    },
    heroTitle: {
      color: colors.text,
      fontSize: 28,
      fontWeight: '700',
      lineHeight: 34,
      marginTop: 4,
    },
    heroMeta: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 6,
      marginTop: 12,
    },
    heroMetaText: {
      color: colors.primary,
      fontSize: 13,
      fontWeight: '600',
    },
    heroArt: {
      borderRadius: 20,
      height: 108,
      marginLeft: 8,
      marginTop: 12,
      width: 108,
      zIndex: 1,
    },
    actions: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: 4,
    },
    actionItem: {
      alignItems: 'center',
      gap: 8,
      width: 58,
    },
    actionIcon: {
      alignItems: 'center',
      borderColor: colors.border,
      borderRadius: 28,
      borderWidth: 1.5,
      height: 56,
      justifyContent: 'center',
      width: 56,
    },
    actionLabel: {
      color: colors.text,
      fontSize: 12,
      fontWeight: '600',
    },
    setupBanner: {
      alignItems: 'center',
      backgroundColor: colors.primary,
      borderRadius: 18,
      flexDirection: 'row',
      paddingHorizontal: 18,
      paddingVertical: 16,
    },
    setupText: {
      color: colors.onPrimary,
      flex: 1,
      fontSize: 15,
      fontWeight: '600',
    },
    setupClose: {
      marginLeft: 8,
    },
    sectionHead: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 4,
    },
    sectionTitle: {
      color: colors.text,
      fontSize: 20,
      fontWeight: '700',
    },
    newsCard: {
      alignItems: 'center',
      backgroundColor: colors.primary,
      borderRadius: 22,
      flexDirection: 'row',
      gap: 14,
      paddingHorizontal: 18,
      paddingVertical: 22,
    },
    newsRail: {
      alignItems: 'center',
      height: 56,
      width: 14,
    },
    newsDot: {
      backgroundColor: colors.accent,
      borderRadius: 6,
      height: 12,
      width: 12,
    },
    newsLine: {
      backgroundColor: colors.accent,
      flex: 1,
      marginTop: 4,
      opacity: 0.45,
      width: 2,
    },
    newsCopy: {
      flex: 1,
    },
    newsTitle: {
      color: colors.onPrimary,
      fontSize: 22,
      fontWeight: '700',
      lineHeight: 28,
    },
    newsMeta: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 6,
      marginTop: 8,
    },
    newsMetaText: {
      color: colors.accent,
      fontSize: 13,
    },
    newsCheck: {
      alignItems: 'center',
      backgroundColor: colors.accent,
      borderRadius: 18,
      height: 36,
      justifyContent: 'center',
      width: 36,
    },
    adminScreen: {
      backgroundColor: colors.background,
      flex: 1,
      paddingHorizontal: 20,
      paddingTop: 24,
    },
    adminBody: {
      alignItems: 'center',
      flex: 1,
      justifyContent: 'center',
    },
    adminLogo: {
      borderRadius: 36,
      height: 180,
      width: 180,
    },
  });
